import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * FAQ
 * Id: e81a6b21-80dc-4ea4-bddc-655b98fae63e
 * Codename: faq
 */
export type FAQ = IContentItem<{
    /**
     * Answer (rich_text)
     * Required: false
     * Id: 689d332e-0bab-4cc1-b750-37554534e5ef
     * Codename: answer
     */
    answer: Elements.RichTextElement;

    /**
     * Question (text)
     * Required: false
     * Id: bf979688-6978-410f-acc4-98d67d2b1733
     * Codename: question
     */
    question: Elements.TextElement;
}>;
