import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Page
 * Id: 8960d4e8-2674-4e08-b00c-fbc18ab79bcf
 * Codename: page
 */
export type Page = IContentItem<{
    /**
     * Body (rich_text)
     * Required: false
     * Id: 7a119590-9f52-4fc9-a659-dbf9fac86c41
     * Codename: body
     */
    body: Elements.RichTextElement;
}>;
