/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const assetFolders = {
    /**
     * Caf  locations
     */
    caféLocations: {
        id: '958001d8-2228-4373-b966-5262b5b96f71',
        name: 'Café locations',
        externalId: undefined,
        folders: {}
    }
} as const;
