/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 */
export const roles = {
    /**
     * Project manager
     */
    projectManager: {
        codename: 'project-manager',
        id: '8d86a04d-ed17-40f1-b6e8-95e2039ca102',
        name: 'Project manager'
    }
} as const;
